version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9@sha256:98e9b26570f26e58bc249f5009f25642f8ff976f38562ec91c4764769d5aa169
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
