version: 2
jobs:
  build:
    branches:
      ignore:
      - gh-pages
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing latest Git
          command: |
            sudo add-apt-repository ppa:git-core/ppa -y
            sudo apt-get update
            sudo apt-get install realpath
            sudo apt-get install git
            which git

      - run:
          name: Installing Node 10
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.9/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 10
            nvm alias default 10
            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV

      - run:
          name: Installing Yarn
          command: |
            set +e
            sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update
            sudo apt-get install yarn

      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Deploy Website
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "dotansimha@users.noreply.github.com"
              git config --global user.name "Dotan Simha"
              echo "machine github.com login dotansimha password $GITHUB_TOKEN" > ~/.netrc
              yarn deploy-website
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
