version: 2
jobs:
  build:
    branches:
      ignore:
      - gh-pages
    docker:
      - image: circleci/node:10.9.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Deploy Website
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "dotansimha@users.noreply.github.com"
              git config --global user.name "Dotan Simha"
              echo "machine github.com login dotansimha password $GITHUB_TOKEN" > ~/.netrc
              yarn deploy-website
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
