version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
