version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9@sha256:69e829c1f2a9f1986c6e2164f1e9028479cf4b044d070220f6386af1502228cf
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
