version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9@sha256:1674de1c1aac495a922b3b0028351f92c937b2318d4d8c4775adeeb7d0f1e22a
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
